package Vistas;

import Modelos.Configuracion;
import Modelos.Productos;
import Modelos.ProductosDao;
import Modelos.Proveedor;
import Modelos.ProveedorDao;
import Modelos.UsuarioDao;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author EDISSON
 */
public class Impresion extends javax.swing.JFrame {

    Productos pro = new Productos();
    ProductosDao proDao = new ProductosDao();
    Configuracion cof = new Configuracion();
    UsuarioDao usDao = new UsuarioDao();
    Proveedor pr = new Proveedor();
    ProveedorDao prDao = new ProveedorDao();
    DefaultTableModel modelo = new DefaultTableModel();
    public Impresion(int id) {
        initComponents();
        Folio.setText("" + id);
        listar(id);
        calcularCompra();
         cof = usDao.getConfig();
        txtRucPrint.setText(cof.getRuc());
        txtNombrePrint.setText(cof.getNombre());
        pr = prDao.getDatos(id);
        txtNombrePr.setText(pr.getNombre());
        txtDireccionPr.setText(pr.getDireccion());
    }
    public void listar(int id) {
        List<Productos> lista = proDao.ListaDetalle(id);
        modelo = (DefaultTableModel) TableDetalle.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < lista.size(); i++) {
            ob[0] = lista.get(i).getCantidad();
            ob[1] = lista.get(i).getDescripcion();
            ob[2] = lista.get(i).getPrecio_compra();
            ob[3] = lista.get(i).getPrecio_venta();
            modelo.addRow(ob);
        }
        TableDetalle.setModel(modelo);
        JTableHeader header = TableDetalle.getTableHeader();
        header.setOpaque(false);
        header.setBackground(Color.blue);
        header.setForeground(Color.white);
    }
    
    private void calcularCompra() {
        double total = 0.00;
        int numFila = TableDetalle.getRowCount();
        for (int i = 0; i < numFila; i++) {
            total = total + Double.parseDouble(String.valueOf(TableDetalle.getValueAt(i, 3)));

        }
        TotalPagar.setText("" + total);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrint = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDetalle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TotalPagar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Folio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRucPrint = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombrePrint = new javax.swing.JLabel();
        txtNombrePr = new javax.swing.JLabel();
        txtDireccionPr = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrint.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Descripción", "Precio", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(TableDetalle);
        if (TableDetalle.getColumnModel().getColumnCount() > 0) {
            TableDetalle.getColumnModel().getColumn(0).setPreferredWidth(15);
            TableDetalle.getColumnModel().getColumn(1).setPreferredWidth(250);
            TableDetalle.getColumnModel().getColumn(2).setPreferredWidth(30);
            TableDetalle.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        PanelPrint.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 590, 440));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("NOMBRE:");
        PanelPrint.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("DIRECCIÓN:");
        PanelPrint.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("TOTAL:");
        PanelPrint.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, -1, -1));

        TotalPagar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TotalPagar.setText("Q0.00");
        PanelPrint.add(TotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, 80, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("INFORME");
        PanelPrint.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("NIT:");
        PanelPrint.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("FOLIO");
        PanelPrint.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        Folio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Folio.setText("1");
        PanelPrint.add(Folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 20, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("DATOS DEL PROVEEDOR");
        PanelPrint.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtRucPrint.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtRucPrint.setText("001");
        PanelPrint.add(txtRucPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 110, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("NOMBRE DE EMPRESA:");
        PanelPrint.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtNombrePrint.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        PanelPrint.add(txtNombrePrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 130, 20));

        txtNombrePr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNombrePr.setForeground(new java.awt.Color(204, 0, 51));
        txtNombrePr.setText("jLabel8");
        PanelPrint.add(txtNombrePr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        txtDireccionPr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDireccionPr.setForeground(new java.awt.Color(204, 0, 51));
        txtDireccionPr.setText("jLabel10");
        PanelPrint.add(txtDireccionPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 230, -1));

        getContentPane().add(PanelPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 680));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton1.setText("IMPRIMIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 690, 180, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Toolkit tk = PanelPrint.getToolkit();
        PrintJob pj = tk.getPrintJob(this, null, null);
        Graphics g = pj.getGraphics();
        PanelPrint.print(g);
        g.dispose();
        pj.end();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Folio;
    private javax.swing.JPanel PanelPrint;
    private javax.swing.JTable TableDetalle;
    private javax.swing.JLabel TotalPagar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtDireccionPr;
    private javax.swing.JLabel txtNombrePr;
    private javax.swing.JLabel txtNombrePrint;
    private javax.swing.JLabel txtRucPrint;
    // End of variables declaration//GEN-END:variables
}
