package Vistas;

import Controles.CategoriasControladores;
import Controles.ClientesControlador;
import Controles.ConfigControles;
import Controles.MedidasControlador;
import Controles.ProductosControlador;
import Controles.ProveedorControlador;
import Controles.UsuariosControladores;
import Modelos.Clientes;
import Modelos.ClientesDao;
import Modelos.UsuarioDao;
import Modelos.Usuarios;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import Modelos.Categorias;
import Modelos.CategoriasDao;
import Modelos.Configuracion;
import Modelos.Medidas;
import Modelos.MedidasDao;
import Modelos.Productos;
import Modelos.ProductosDao;
import Modelos.Proveedor;
import Modelos.ProveedorDao;

/**
 *
 * @author EDISSON
 */
public class PanelAdmin extends javax.swing.JFrame {

    Usuarios us = new Usuarios();
    UsuarioDao usDao = new UsuarioDao();
    Clientes cl = new Clientes();
    ClientesDao clDao = new ClientesDao();
    Categorias cat = new Categorias();
    CategoriasDao catDao = new CategoriasDao();
    Medidas med = new Medidas();
    MedidasDao medDao = new MedidasDao();
    Proveedor prov = new Proveedor();
    ProveedorDao provDao = new ProveedorDao();
    Productos pro = new Productos();
    ProductosDao proDao = new ProductosDao();
    Configuracion cof = new Configuracion();
    public PanelAdmin() {

        initComponents();
        ConfigControles config = new ConfigControles(cof, usDao, this);
        UsuariosControladores users = new UsuariosControladores(us, usDao, this);
        ClientesControlador cliente = new ClientesControlador(cl, clDao, this);
        CategoriasControladores categoria = new CategoriasControladores(cat, catDao, this);
        MedidasControlador medida = new MedidasControlador(med, medDao, this);
        ProveedorControlador proveedor = new ProveedorControlador(prov, provDao, this);
        ProductosControlador producto = new ProductosControlador(pro, proDao, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPopupUsuarios = new javax.swing.JPopupMenu();
        JMenuEliminarUsers = new javax.swing.JMenuItem();
        JMenuReingresarUsers = new javax.swing.JMenuItem();
        JPopupClientes = new javax.swing.JPopupMenu();
        JMenuEliminarCli = new javax.swing.JMenuItem();
        JMenuReingresarCli = new javax.swing.JMenuItem();
        jPopupCategoria = new javax.swing.JPopupMenu();
        JMenuEliminarCat = new javax.swing.JMenuItem();
        JMenuReingresarCat = new javax.swing.JMenuItem();
        jPopupMedida = new javax.swing.JPopupMenu();
        JMenuEliminarMed = new javax.swing.JMenuItem();
        JMenuReingresarMed = new javax.swing.JMenuItem();
        jPopupProveedor = new javax.swing.JPopupMenu();
        JMenuEliminarProv = new javax.swing.JMenuItem();
        JMenuReingresarProv = new javax.swing.JMenuItem();
        JPopupProductos = new javax.swing.JPopupMenu();
        JMenuEliminarPro = new javax.swing.JMenuItem();
        JMenuReingresarPro = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        JPanelProductos = new javax.swing.JPanel();
        JlabelProductos = new javax.swing.JLabel();
        JPanelClientes = new javax.swing.JPanel();
        JLabelClientes = new javax.swing.JLabel();
        JPanelProveedor = new javax.swing.JPanel();
        JLabelProveedor = new javax.swing.JLabel();
        JPanelCategorias = new javax.swing.JPanel();
        JLabelCat = new javax.swing.JLabel();
        JPanelConfig = new javax.swing.JPanel();
        JLabelConfig = new javax.swing.JLabel();
        JPanelMedidas = new javax.swing.JPanel();
        JLabelMedidas = new javax.swing.JLabel();
        JPanelUsers = new javax.swing.JPanel();
        JLabelUsers = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoPro = new javax.swing.JTextField();
        txtDescripcionPro = new javax.swing.JTextField();
        txtPrecioCompraPro = new javax.swing.JTextField();
        txtPrecioVentaPro = new javax.swing.JTextField();
        cbxProveedorPro = new javax.swing.JComboBox<>();
        cbxMedidaPro = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnNuevoPro = new javax.swing.JButton();
        btnRegistrarPro = new javax.swing.JButton();
        btnModificarPro = new javax.swing.JButton();
        txtIdPro = new javax.swing.JTextField();
        cbxCatPro = new javax.swing.JComboBox<>();
        JLabelId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProductos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombreCli = new javax.swing.JTextField();
        txtTelefonoCli = new javax.swing.JTextField();
        btnNuevoCli = new javax.swing.JButton();
        btnModificarCli = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDireccionCli = new javax.swing.JTextPane();
        btnRegistrarCliente = new javax.swing.JButton();
        txtIdCli = new javax.swing.JTextField();
        txtBuscarCli = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableClientes = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombreProv = new javax.swing.JTextField();
        txtTelefonoProv = new javax.swing.JTextField();
        btnNuevoProv = new javax.swing.JButton();
        btnRegistrarProv = new javax.swing.JButton();
        btnModificarProv = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDireccionProv = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        txtRucProv = new javax.swing.JTextField();
        txtIdProv = new javax.swing.JTextField();
        txtBuscarProv = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableProveedor = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNombreUser = new javax.swing.JTextField();
        btnNuevoUser = new javax.swing.JButton();
        btnRegistrarUser = new javax.swing.JButton();
        btnModificarUser = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        cbxRolUser = new javax.swing.JComboBox<>();
        cbxCajaUser = new javax.swing.JComboBox<>();
        txtClaveUser = new javax.swing.JPasswordField();
        jLabel50 = new javax.swing.JLabel();
        txtIdUser = new javax.swing.JTextField();
        txtUsuarioUser = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txtBuscarUsers = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TableUsers = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtNombreCat = new javax.swing.JTextField();
        txtBuscarCat = new javax.swing.JTextField();
        txtIdCat = new javax.swing.JTextField();
        btnNuevoCat = new javax.swing.JButton();
        btnRegitrarCat = new javax.swing.JButton();
        btnModificarCat = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        TableCat = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtNombreCortoMed = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtNombreMed = new javax.swing.JTextField();
        txtBuscarMed = new javax.swing.JTextField();
        btnNuevoMed = new javax.swing.JButton();
        btnRegitrarMed = new javax.swing.JButton();
        btnModificarMed = new javax.swing.JButton();
        txtIdMed = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        TableMedida = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txtRucEmpresa = new javax.swing.JTextField();
        txtTelefonoEmpresa = new javax.swing.JTextField();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtDireccionEmpresa = new javax.swing.JTextPane();
        txtNombreEmpresa = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextPane();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        TableNuevaCompra = new javax.swing.JTable();
        JLabelTotalCompra = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtVueltoNC = new javax.swing.JTextField();
        txtProductoNC = new javax.swing.JTextField();
        txtCantNC = new javax.swing.JTextField();
        txtPrecioNC = new javax.swing.JTextField();
        txtTotalNC = new javax.swing.JTextField();
        btnGenerarCompra = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        cbxProCompra = new javax.swing.JComboBox<>();
        txtCodNC = new javax.swing.JTextField();
        txtPagarConNC = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        txtIdNC = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();

        JMenuEliminarUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar-amigo.png"))); // NOI18N
        JMenuEliminarUsers.setText("Borrar");
        JPopupUsuarios.add(JMenuEliminarUsers);

        JMenuReingresarUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        JMenuReingresarUsers.setText("Reingresar");
        JPopupUsuarios.add(JMenuReingresarUsers);

        JMenuEliminarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar-amigo.png"))); // NOI18N
        JMenuEliminarCli.setText("BORRAR");
        JPopupClientes.add(JMenuEliminarCli);

        JMenuReingresarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        JMenuReingresarCli.setText("REINGRESAR");
        JPopupClientes.add(JMenuReingresarCli);

        JMenuEliminarCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar-amigo.png"))); // NOI18N
        JMenuEliminarCat.setText("ELIMINAR");
        jPopupCategoria.add(JMenuEliminarCat);

        JMenuReingresarCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        JMenuReingresarCat.setText("REINGRESAR");
        jPopupCategoria.add(JMenuReingresarCat);

        JMenuEliminarMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar-amigo.png"))); // NOI18N
        JMenuEliminarMed.setText("ELIMINAR");
        jPopupMedida.add(JMenuEliminarMed);

        JMenuReingresarMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        JMenuReingresarMed.setText("REINGRESAR");
        jPopupMedida.add(JMenuReingresarMed);

        JMenuEliminarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar-amigo.png"))); // NOI18N
        JMenuEliminarProv.setText("ELIMINAR");
        jPopupProveedor.add(JMenuEliminarProv);

        JMenuReingresarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        JMenuReingresarProv.setText("REINGRESAR");
        jPopupProveedor.add(JMenuReingresarProv);

        JMenuEliminarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar-amigo.png"))); // NOI18N
        JMenuEliminarPro.setText("ELIMINAR");
        JPopupProductos.add(JMenuEliminarPro);

        JMenuReingresarPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        JMenuReingresarPro.setText("REINGRESAR");
        JPopupProductos.add(JMenuReingresarPro);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelProductos.setBackground(new java.awt.Color(0, 153, 153));

        JlabelProductos.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        JlabelProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlabelProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/paquete.png"))); // NOI18N
        JlabelProductos.setText("PRODUCTOS");
        JlabelProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelProductosLayout = new javax.swing.GroupLayout(JPanelProductos);
        JPanelProductos.setLayout(JPanelProductosLayout);
        JPanelProductosLayout.setHorizontalGroup(
            JPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelProductosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(JlabelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        JPanelProductosLayout.setVerticalGroup(
            JPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelProductosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JlabelProductos)
                .addContainerGap())
        );

        jPanel1.add(JPanelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 180, 50));

        JPanelClientes.setBackground(new java.awt.Color(0, 153, 153));

        JLabelClientes.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        JLabelClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        JLabelClientes.setText("CLIENTES");
        JLabelClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelClientesLayout = new javax.swing.GroupLayout(JPanelClientes);
        JPanelClientes.setLayout(JPanelClientesLayout);
        JPanelClientesLayout.setHorizontalGroup(
            JPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClientesLayout.createSequentialGroup()
                .addComponent(JLabelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPanelClientesLayout.setVerticalGroup(
            JPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(JPanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 200, 40));

        JPanelProveedor.setBackground(new java.awt.Color(0, 153, 153));

        JLabelProveedor.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        JLabelProveedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedor.png"))); // NOI18N
        JLabelProveedor.setText("PROVEEDORES");
        JLabelProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelProveedorLayout = new javax.swing.GroupLayout(JPanelProveedor);
        JPanelProveedor.setLayout(JPanelProveedorLayout);
        JPanelProveedorLayout.setHorizontalGroup(
            JPanelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelProveedorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLabelProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JPanelProveedorLayout.setVerticalGroup(
            JPanelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelProveedorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLabelProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(JPanelProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 40, 200, 40));

        JPanelCategorias.setBackground(new java.awt.Color(0, 153, 153));

        JLabelCat.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        JLabelCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/categorias.png"))); // NOI18N
        JLabelCat.setText("CATEGORIAS");
        JLabelCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelCategoriasLayout = new javax.swing.GroupLayout(JPanelCategorias);
        JPanelCategorias.setLayout(JPanelCategoriasLayout);
        JPanelCategoriasLayout.setHorizontalGroup(
            JPanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCategoriasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLabelCat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JPanelCategoriasLayout.setVerticalGroup(
            JPanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCategoriasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLabelCat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(JPanelCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 200, 40));

        JPanelConfig.setBackground(new java.awt.Color(0, 153, 153));

        JLabelConfig.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        JLabelConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion.png"))); // NOI18N
        JLabelConfig.setText("CONFIGURACION");
        JLabelConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelConfigLayout = new javax.swing.GroupLayout(JPanelConfig);
        JPanelConfig.setLayout(JPanelConfigLayout);
        JPanelConfigLayout.setHorizontalGroup(
            JPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConfigLayout.createSequentialGroup()
                .addComponent(JLabelConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPanelConfigLayout.setVerticalGroup(
            JPanelConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConfigLayout.createSequentialGroup()
                .addComponent(JLabelConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 200, 40));

        JPanelMedidas.setBackground(new java.awt.Color(0, 153, 153));

        JLabelMedidas.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        JLabelMedidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelMedidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reduccion-de-peso.png"))); // NOI18N
        JLabelMedidas.setText("MEDIDAS");
        JLabelMedidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelMedidasLayout = new javax.swing.GroupLayout(JPanelMedidas);
        JPanelMedidas.setLayout(JPanelMedidasLayout);
        JPanelMedidasLayout.setHorizontalGroup(
            JPanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMedidasLayout.createSequentialGroup()
                .addComponent(JLabelMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        JPanelMedidasLayout.setVerticalGroup(
            JPanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelMedidasLayout.createSequentialGroup()
                .addComponent(JLabelMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(JPanelMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, 40));

        JPanelUsers.setBackground(new java.awt.Color(0, 153, 153));

        JLabelUsers.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        JLabelUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grupo.png"))); // NOI18N
        JLabelUsers.setText("USUARIOS");
        JLabelUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelUsersLayout = new javax.swing.GroupLayout(JPanelUsers);
        JPanelUsers.setLayout(JPanelUsersLayout);
        JPanelUsersLayout.setHorizontalGroup(
            JPanelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelUsersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLabelUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JPanelUsersLayout.setVerticalGroup(
            JPanelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelUsersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JLabelUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(JPanelUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 200, 40));
        jPanel1.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, 0));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compras.png"))); // NOI18N
        jButton1.setText("NUEVA COMPRA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1330, 200));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA DE COMPRAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(523, 523, 523)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(551, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 70));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("NUEVO PRODUCTO"));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel2.setText("CODIGO");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel3.setText("DESCRIPCION");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel4.setText("PRECIO DE COMPRA");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel6.setText("PRECIO DE VENTA");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel7.setText("PROVEEDOR");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel8.setText("MEDIDA");

        txtCodigoPro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtDescripcionPro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtPrecioCompraPro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtPrecioVentaPro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        cbxProveedorPro.setEditable(true);
        cbxProveedorPro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        cbxMedidaPro.setEditable(true);
        cbxMedidaPro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        jLabel9.setText("CATEGORIA");

        btnNuevoPro.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnNuevoPro.setText("NUEVO");

        btnRegistrarPro.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnRegistrarPro.setText("REGISTRAR");

        btnModificarPro.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnModificarPro.setText("MODIFICAR");

        txtIdPro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        cbxCatPro.setEditable(true);
        cbxCatPro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        JLabelId.setFont(new java.awt.Font("Trebuchet MS", 3, 13)); // NOI18N
        JLabelId.setText("ID");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtPrecioVentaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel6))
                                            .addGap(126, 126, 126))
                                        .addComponent(txtPrecioCompraPro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(112, 112, 112))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxProveedorPro, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxMedidaPro, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDescripcionPro, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbxCatPro, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(JLabelId))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdPro, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnNuevoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(btnRegistrarPro)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarPro)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtCodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescripcionPro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecioCompraPro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioVentaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(cbxProveedorPro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8)
                        .addGap(3, 3, 3)
                        .addComponent(cbxMedidaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12)
                        .addComponent(cbxCatPro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 590));

        TableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Codigo", "Descripcion", "Precio", "Stock", "Estado"
            }
        ));
        TableProductos.setComponentPopupMenu(JPopupProductos);
        jScrollPane1.setViewportView(TableProductos);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 870, 580));

        jTabbedPane1.addTab("tab1", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 102, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("NUEVO CLIENTE"));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel10.setText("ID");
        jPanel16.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 20, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel11.setText("TELEFONO");
        jPanel16.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel12.setText("DIRECCION");
        jPanel16.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        txtNombreCli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel16.add(txtNombreCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 280, 32));

        txtTelefonoCli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel16.add(txtTelefonoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 280, 32));

        btnNuevoCli.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnNuevoCli.setText("NUEVO");
        jPanel16.add(btnNuevoCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 97, 32));

        btnModificarCli.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnModificarCli.setText("MODIFICAR");
        jPanel16.add(btnModificarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, 32));

        txtDireccionCli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(txtDireccionCli);

        jPanel16.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 270, 30));

        btnRegistrarCliente.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnRegistrarCliente.setText("REGISTRAR");
        jPanel16.add(btnRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 130, 30));

        txtIdCli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel16.add(txtIdCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 70, -1));

        txtBuscarCli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel16.add(txtBuscarCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 280, 30));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel19.setText("NOMBRE DEL CLIENTE");
        jPanel16.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        jPanel16.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, -1));

        jPanel5.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 424, 580));

        TableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Telefono", "Dirección", "Estado"
            }
        ));
        TableClientes.setComponentPopupMenu(JPopupClientes);
        jScrollPane2.setViewportView(TableClientes);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 15, 860, 580));

        jTabbedPane1.addTab("tab2", jPanel5);

        jPanel6.setBackground(new java.awt.Color(0, 204, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("NUEVO PROVEEDOR"));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel13.setText("NOMBRE");
        jPanel17.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel14.setText("TELEFONO");
        jPanel17.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel15.setText("DIRECCION");
        jPanel17.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        txtNombreProv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel17.add(txtNombreProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 280, 30));

        txtTelefonoProv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel17.add(txtTelefonoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 280, 30));

        btnNuevoProv.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnNuevoProv.setText("NUEVO");
        jPanel17.add(btnNuevoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 97, 32));

        btnRegistrarProv.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnRegistrarProv.setText("REGISTRAR");
        jPanel17.add(btnRegistrarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, -1, 32));

        btnModificarProv.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnModificarProv.setText("MODIFICAR");
        jPanel17.add(btnModificarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, -1, 32));

        txtDireccionProv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane4.setViewportView(txtDireccionProv);

        jPanel17.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 270, 70));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel16.setText("ID");
        jPanel17.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtRucProv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel17.add(txtRucProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 280, 30));

        txtIdProv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIdProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProvActionPerformed(evt);
            }
        });
        jPanel17.add(txtIdProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 80, 20));

        txtBuscarProv.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel17.add(txtBuscarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 280, 30));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        jPanel17.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel27.setText("NIT");
        jPanel17.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jPanel6.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 600));

        TableProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "NIT", "Nombre", "Telefono", "Direccion", "Estado"
            }
        ));
        TableProveedor.setComponentPopupMenu(jPopupProveedor);
        jScrollPane5.setViewportView(TableProveedor);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 860, 600));

        jTabbedPane1.addTab("tab3", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 204, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("NUEVO USUARIO"));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel17.setText("NOMBRE");
        jPanel18.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel18.setText("CONTRASEÑA:");
        jPanel18.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txtNombreUser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel18.add(txtNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 280, 30));

        btnNuevoUser.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnNuevoUser.setText("NUEVO");
        jPanel18.add(btnNuevoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 97, 32));

        btnRegistrarUser.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnRegistrarUser.setText("REGISTRAR");
        jPanel18.add(btnRegistrarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, 32));

        btnModificarUser.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnModificarUser.setText("MODIFICAR");
        jPanel18.add(btnModificarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, 32));

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel20.setText("ID");
        jPanel18.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel21.setText("CAJA:");
        jPanel18.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        cbxRolUser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxRolUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador" }));
        jPanel18.add(cbxRolUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 270, 30));

        cbxCajaUser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxCajaUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "general" }));
        jPanel18.add(cbxCajaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 270, 30));

        txtClaveUser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel18.add(txtClaveUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 280, 30));

        jLabel50.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel50.setText("ROL");
        jPanel18.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        txtIdUser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel18.add(txtIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 70, -1));

        txtUsuarioUser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel18.add(txtUsuarioUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 280, 30));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        jPanel18.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 40, -1));

        txtBuscarUsers.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel18.add(txtBuscarUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 280, 30));

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel28.setText("USUARIO:");
        jPanel18.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jPanel7.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 600));

        TableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Usuario", "Nombre", "Caja", "Rol", "Estado"
            }
        ));
        TableUsers.setComponentPopupMenu(JPopupUsuarios);
        TableUsers.setRowHeight(22);
        jScrollPane7.setViewportView(TableUsers);

        jPanel7.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 850, 600));

        jTabbedPane1.addTab("tab4", jPanel7);

        jPanel8.setBackground(new java.awt.Color(102, 153, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("NUEVO CATEGORIA"));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel22.setText("ID");
        jPanel19.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtNombreCat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel19.add(txtNombreCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 280, 30));

        txtBuscarCat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel19.add(txtBuscarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 270, 30));

        txtIdCat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel19.add(txtIdCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 60, -1));

        btnNuevoCat.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnNuevoCat.setText("NUEVO");
        jPanel19.add(btnNuevoCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        btnRegitrarCat.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnRegitrarCat.setText("REGISTRAR");
        jPanel19.add(btnRegitrarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        btnModificarCat.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnModificarCat.setText("MODIFICAR");
        jPanel19.add(btnModificarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        jPanel19.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel30.setText("NOMBRE");
        jPanel19.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jPanel8.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 350));

        TableCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Estado"
            }
        ));
        TableCat.setComponentPopupMenu(jPopupCategoria);
        jScrollPane8.setViewportView(TableCat);

        jPanel8.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 860, 570));

        jTabbedPane1.addTab("tab5", jPanel8);

        jPanel9.setBackground(new java.awt.Color(0, 255, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("NUEVO MEDIDA"));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel23.setText("NOMBRE ABREVIADO");
        jPanel20.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        txtNombreCortoMed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel20.add(txtNombreCortoMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 280, 30));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel24.setText("ID");
        jPanel20.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtNombreMed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel20.add(txtNombreMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 280, 30));

        txtBuscarMed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel20.add(txtBuscarMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 270, 30));

        btnNuevoMed.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnNuevoMed.setText("NUEVO");
        jPanel20.add(btnNuevoMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        btnRegitrarMed.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnRegitrarMed.setText("REGISTRAR");
        jPanel20.add(btnRegitrarMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        btnModificarMed.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnModificarMed.setText("MODIFICAR");
        jPanel20.add(btnModificarMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));

        txtIdMed.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel20.add(txtIdMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        jPanel20.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, -1));

        jLabel32.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel32.setText("NOMBRE DE LA MEDIDA");
        jPanel20.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jPanel9.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 580));

        TableMedida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Nombre Abreviado", "Estado"
            }
        ));
        TableMedida.setComponentPopupMenu(jPopupMedida);
        jScrollPane9.setViewportView(TableMedida);

        jPanel9.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 860, 580));

        jTabbedPane1.addTab("tab6", jPanel9);

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMACION DE LA EMPRESA"));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel25.setText("NIT");
        jPanel21.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel40.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel40.setText("TELEFONO");
        jPanel21.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel46.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel46.setText("MENSAJE");
        jPanel21.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        txtRucEmpresa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel21.add(txtRucEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 290, 32));

        txtTelefonoEmpresa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel21.add(txtTelefonoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 290, 32));

        txtDireccionEmpresa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane13.setViewportView(txtDireccionEmpresa);

        jPanel21.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 290, 100));

        txtNombreEmpresa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel21.add(txtNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 290, 32));

        jLabel47.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel47.setText("NOMBRE");
        jPanel21.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel48.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel48.setText("DIRECCION");
        jPanel21.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtMensaje.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jScrollPane14.setViewportView(txtMensaje);

        jPanel21.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 290, 60));

        jPanel13.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 424, 500));

        jTabbedPane1.addTab("tab10", jPanel13);

        jPanel15.setBackground(new java.awt.Color(102, 204, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableNuevaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripción", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane10.setViewportView(TableNuevaCompra);

        jPanel15.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1260, 360));

        JLabelTotalCompra.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        JLabelTotalCompra.setForeground(new java.awt.Color(255, 51, 51));
        JLabelTotalCompra.setText("00.00");
        jPanel15.add(JLabelTotalCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 540, 140, -1));

        jLabel36.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel36.setText("PRODUCTO:");
        jPanel15.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel37.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel37.setText("CANTIDAD:");
        jPanel15.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel38.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel38.setText("PRECIO:");
        jPanel15.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        jLabel39.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel39.setText("ID");
        jPanel15.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        txtVueltoNC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel15.add(txtVueltoNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 140, -1));

        txtProductoNC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel15.add(txtProductoNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 120, -1));

        txtCantNC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel15.add(txtCantNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 120, 20));

        txtPrecioNC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel15.add(txtPrecioNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 120, -1));

        txtTotalNC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel15.add(txtTotalNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 120, -1));

        btnGenerarCompra.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnGenerarCompra.setText("GENERAR COMPRA");
        jPanel15.add(btnGenerarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 70, 200, 40));

        jLabel41.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel41.setText("CODIGO:");
        jPanel15.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        cbxProCompra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel15.add(cbxProCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 170, -1));

        txtCodNC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel15.add(txtCodNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, -1));

        txtPagarConNC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel15.add(txtPagarConNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 150, -1));

        jLabel42.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel42.setText("EL VUELTO ES:");
        jPanel15.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, -1, -1));

        jLabel43.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel43.setText("TOTAL A PAGAR:");
        jPanel15.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 540, -1, -1));

        jLabel44.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel44.setText("PROVEEDOR:");
        jPanel15.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        jLabel45.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel45.setText("PAGA CON:");
        jPanel15.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, -1));

        txtIdNC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel15.add(txtIdNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 90, -1));

        jLabel52.setFont(new java.awt.Font("Trebuchet MS", 3, 20)); // NOI18N
        jLabel52.setText("TOTAL:");
        jPanel15.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, -1, -1));

        jTabbedPane1.addTab("NUEVA COMPRA", jPanel15);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1330, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProvActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(7);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JLabelCat;
    public javax.swing.JLabel JLabelClientes;
    public javax.swing.JLabel JLabelConfig;
    private javax.swing.JLabel JLabelId;
    public javax.swing.JLabel JLabelMedidas;
    public javax.swing.JLabel JLabelProveedor;
    public javax.swing.JLabel JLabelTotalCompra;
    public javax.swing.JLabel JLabelUsers;
    public javax.swing.JMenuItem JMenuEliminarCat;
    public javax.swing.JMenuItem JMenuEliminarCli;
    public javax.swing.JMenuItem JMenuEliminarMed;
    public javax.swing.JMenuItem JMenuEliminarPro;
    public javax.swing.JMenuItem JMenuEliminarProv;
    public javax.swing.JMenuItem JMenuEliminarUsers;
    public javax.swing.JMenuItem JMenuReingresarCat;
    public javax.swing.JMenuItem JMenuReingresarCli;
    public javax.swing.JMenuItem JMenuReingresarMed;
    public javax.swing.JMenuItem JMenuReingresarPro;
    public javax.swing.JMenuItem JMenuReingresarProv;
    public javax.swing.JMenuItem JMenuReingresarUsers;
    public javax.swing.JPanel JPanelCategorias;
    public javax.swing.JPanel JPanelClientes;
    public javax.swing.JPanel JPanelConfig;
    public javax.swing.JPanel JPanelMedidas;
    public javax.swing.JPanel JPanelProductos;
    public javax.swing.JPanel JPanelProveedor;
    public javax.swing.JPanel JPanelUsers;
    private javax.swing.JPopupMenu JPopupClientes;
    private javax.swing.JPopupMenu JPopupProductos;
    private javax.swing.JPopupMenu JPopupUsuarios;
    public javax.swing.JLabel JlabelProductos;
    public javax.swing.JTable TableCat;
    public javax.swing.JTable TableClientes;
    public javax.swing.JTable TableMedida;
    public javax.swing.JTable TableNuevaCompra;
    public javax.swing.JTable TableProductos;
    public javax.swing.JTable TableProveedor;
    public javax.swing.JTable TableUsers;
    public javax.swing.JButton btnGenerarCompra;
    public javax.swing.JButton btnModificarCat;
    public javax.swing.JButton btnModificarCli;
    public javax.swing.JButton btnModificarMed;
    public javax.swing.JButton btnModificarPro;
    public javax.swing.JButton btnModificarProv;
    public javax.swing.JButton btnModificarUser;
    public javax.swing.JButton btnNuevoCat;
    public javax.swing.JButton btnNuevoCli;
    public javax.swing.JButton btnNuevoMed;
    public javax.swing.JButton btnNuevoPro;
    public javax.swing.JButton btnNuevoProv;
    public javax.swing.JButton btnNuevoUser;
    public javax.swing.JButton btnRegistrarCliente;
    public javax.swing.JButton btnRegistrarPro;
    public javax.swing.JButton btnRegistrarProv;
    public javax.swing.JButton btnRegistrarUser;
    public javax.swing.JButton btnRegitrarCat;
    public javax.swing.JButton btnRegitrarMed;
    public javax.swing.JComboBox<String> cbxCajaUser;
    public javax.swing.JComboBox<Object> cbxCatPro;
    public javax.swing.JComboBox<Object> cbxMedidaPro;
    public javax.swing.JComboBox<Object> cbxProCompra;
    public javax.swing.JComboBox<Object> cbxProveedorPro;
    public javax.swing.JComboBox<String> cbxRolUser;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupCategoria;
    private javax.swing.JPopupMenu jPopupMedida;
    private javax.swing.JPopupMenu jPopupProveedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField txtBuscarCat;
    public javax.swing.JTextField txtBuscarCli;
    public javax.swing.JTextField txtBuscarMed;
    public javax.swing.JTextField txtBuscarProducto;
    public javax.swing.JTextField txtBuscarProv;
    public javax.swing.JTextField txtBuscarUsers;
    public javax.swing.JTextField txtCantNC;
    public javax.swing.JPasswordField txtClaveUser;
    public javax.swing.JTextField txtCodNC;
    public javax.swing.JTextField txtCodigoPro;
    public javax.swing.JTextField txtDescripcionPro;
    public javax.swing.JTextPane txtDireccionCli;
    public javax.swing.JTextPane txtDireccionEmpresa;
    public javax.swing.JTextPane txtDireccionProv;
    public javax.swing.JTextField txtIdCat;
    public javax.swing.JTextField txtIdCli;
    public javax.swing.JTextField txtIdMed;
    public javax.swing.JTextField txtIdNC;
    public javax.swing.JTextField txtIdPro;
    public javax.swing.JTextField txtIdProv;
    public javax.swing.JTextField txtIdUser;
    public javax.swing.JTextPane txtMensaje;
    public javax.swing.JTextField txtNombreCat;
    public javax.swing.JTextField txtNombreCli;
    public javax.swing.JTextField txtNombreCortoMed;
    public javax.swing.JTextField txtNombreEmpresa;
    public javax.swing.JTextField txtNombreMed;
    public javax.swing.JTextField txtNombreProv;
    public javax.swing.JTextField txtNombreUser;
    public javax.swing.JTextField txtPagarConNC;
    public javax.swing.JTextField txtPrecioCompraPro;
    public javax.swing.JTextField txtPrecioNC;
    public javax.swing.JTextField txtPrecioVentaPro;
    public javax.swing.JTextField txtProductoNC;
    public javax.swing.JTextField txtRucEmpresa;
    public javax.swing.JTextField txtRucProv;
    public javax.swing.JTextField txtTelefonoCli;
    public javax.swing.JTextField txtTelefonoEmpresa;
    public javax.swing.JTextField txtTelefonoProv;
    public javax.swing.JTextField txtTotalNC;
    public javax.swing.JTextField txtUsuarioUser;
    public javax.swing.JTextField txtVueltoNC;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
}
